# -*- coding: utf-8 -*-
"""Taller3_Punto7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BNZD3er-eUyAmZ_IpeZ3m0I2VtdRGtHI
"""

!pip install mediapipe
!pip install mediapipe_gestures_colab

# mediapipe_gestures_colab.py
# Demo lista para Google Colab: MediaPipe Hands + OpenCV + minijuego "Catch"
# Cambios: opción `mirror=True` por defecto — el frame se voltea horizontalmente ANTES de procesar,
#          de modo que la vista y las etiquetas de mano coinciden con la percepción del usuario.
#
# Uso rápido en Colab:
# 1) Instalar dependencias:
#    !pip install mediapipe opencv-python-headless==4.7.0.72
# 2) Pegar este archivo en una celda (o guardarlo) y ejecutarlo.
# 3) from mediapipe_gestures_colab import run_colab
#    run_colab(max_seconds=None, fps=8, mirror=True)
#
# Para detener: pulsa el botón "Stop Stream" en la esquina superior derecha o interrumpe la celda.

import time
import base64
import cv2
import numpy as np
import mediapipe as mp
from google.colab.output import eval_js
from IPython.display import display, Image as IPyImage

# ------------------ JavaScript snippets ------------------

_JS_INIT_PAGE = r"""
(async () => {
  try {
    if (window._colab_video && window._colab_video.srcObject) {
      return 'already_initialized';
    }
    // Crear video y canvas persistentes en el DOM
    const video = document.createElement('video');
    video.setAttribute('autoplay', '');
    video.setAttribute('playsinline', '');
    video.style.display = 'none';
    document.body.appendChild(video);

    const stream = await navigator.mediaDevices.getUserMedia({video: {width: 640, height: 480}, audio: false});
    video.srcObject = stream;
    await video.play();

    const canvas = document.createElement('canvas');
    canvas.width = 640;
    canvas.height = 480;
    canvas.style.display = 'none';
    document.body.appendChild(canvas);
    const ctx = canvas.getContext('2d');

    // Stop control flag
    window._colab_stream_stop = false;

    window._colab_video = video;
    window._colab_canvas = canvas;
    window._colab_ctx = ctx;
    return 'ok';
  } catch (e) {
    return 'error:' + e.toString();
  }
})();
"""

_JS_CAPTURE_PAGE = r"""
(() => {
  try {
    if (!window._colab_video || !window._colab_canvas || !window._colab_ctx) {
      return '';
    }
    const v = window._colab_video;
    const c = window._colab_canvas;
    const ctx = window._colab_ctx;
    ctx.drawImage(v, 0, 0, c.width, c.height);
    return c.toDataURL('image/jpeg', 0.8);
  } catch (e) {
    return 'error:' + e.toString();
  }
})()
"""

_JS_STOP_PAGE = r"""
(() => {
  try {
    if (window._colab_video && window._colab_video.srcObject) {
      window._colab_video.srcObject.getTracks().forEach(t => t.stop());
    }
    if (window._colab_video && window._colab_video.parentElement) {
      window._colab_video.parentElement.removeChild(window._colab_video);
    }
    if (window._colab_canvas && window._colab_canvas.parentElement) {
      window._colab_canvas.parentElement.removeChild(window._colab_canvas);
    }
    window._colab_stream_stop = false;
    delete window._colab_video;
    delete window._colab_canvas;
    delete window._colab_ctx;
    delete window._colab_stream_stop;
    return 'stopped';
  } catch (e) {
    return 'error:' + e.toString();
  }
})();
"""

_JS_MAKE_STOP_BUTTON = r"""
(() => {
  try {
    if (document.getElementById('_colab_stop_stream_btn')) {
      return 'button_already';
    }
    const btn = document.createElement('button');
    btn.id = '_colab_stop_stream_btn';
    btn.innerText = 'Stop Stream';
    btn.style.position = 'fixed';
    btn.style.zIndex = 999999;
    btn.style.right = '10px';
    btn.style.top = '10px';
    btn.style.padding = '8px 12px';
    btn.style.background = '#c0392b';
    btn.style.color = '#fff';
    btn.style.border = 'none';
    btn.style.borderRadius = '4px';
    btn.style.fontSize = '14px';
    btn.onclick = () => { window._colab_stream_stop = true; btn.innerText = 'Stopping...'; btn.disabled = true; };
    document.body.appendChild(btn);
    return 'button_created';
  } catch (e) {
    return 'error:' + e.toString();
  }
})();
"""

_JS_REMOVE_STOP_BUTTON = r"""
(() => {
  try {
    const btn = document.getElementById('_colab_stop_stream_btn');
    if (btn && btn.parentElement) {
      btn.parentElement.removeChild(btn);
      return 'removed';
    }
    return 'not_found';
  } catch (e) {
    return 'error:' + e.toString();
  }
})();
"""

_JS_CHECK_STOP_FLAG = r"""
(() => {
  try {
    return Boolean(window._colab_stream_stop);
  } catch (e) {
    return false;
  }
})();
"""

# ------------------ JS interaction helpers ------------------

def init_camera_page():
    """Inicializa la cámara en el DOM del navegador. Devuelve el string resultado ('ok', 'already_initialized' o 'error:...')."""
    res = eval_js(_JS_INIT_PAGE)
    print("init_camera_page ->", repr(res))
    return res

def capture_frame_dataurl():
    """Captura un frame y devuelve dataURL o ''/error..."""
    return eval_js(_JS_CAPTURE_PAGE)

def stop_camera_page():
    """Detiene la cámara y limpia nodos en la página."""
    res = eval_js(_JS_STOP_PAGE)
    print("stop_camera_page ->", repr(res))
    # intentar quitar botón si existe
    try:
        eval_js(_JS_REMOVE_STOP_BUTTON)
    except Exception:
        pass
    return res

def make_stop_button():
    """Crea un botón 'Stop Stream' en la página para que el usuario detenga el loop."""
    res = eval_js(_JS_MAKE_STOP_BUTTON)
    print("make_stop_button ->", repr(res))
    return res

def check_stop_requested():
    """Consulta si la página ha marcado la petición de detener el stream."""
    try:
        return bool(eval_js(_JS_CHECK_STOP_FLAG))
    except Exception:
        return False

# ------------------ Utilities ------------------

def dataurl_to_cv2_img(data_url):
    """Convierte dataURL JPEG a imagen OpenCV BGR. Devuelve None si falla."""
    if not data_url:
        return None
    if not isinstance(data_url, str):
        return None
    if data_url.startswith('error:'):
        return None
    try:
        header, encoded = data_url.split(',', 1)
        data = base64.b64decode(encoded)
        arr = np.frombuffer(data, dtype=np.uint8)
        img = cv2.imdecode(arr, cv2.IMREAD_COLOR)
        return img
    except Exception:
        return None

# ------------------ Gesture processing ------------------

mp_drawing = mp.solutions.drawing_utils
mp_hands = mp.solutions.hands

def count_fingers(hand_landmarks, handedness_label):
    tips = [4, 8, 12, 16, 20]
    pip_ids = {4: 3, 8: 6, 12: 10, 16: 14, 20: 18}
    lm = hand_landmarks.landmark
    fingers = {}
    # Thumb: comparación horizontal depende de mano
    try:
        if handedness_label == 'Right':
            fingers['thumb'] = 1 if lm[4].x < lm[3].x else 0
        else:
            fingers['thumb'] = 1 if lm[4].x > lm[3].x else 0
    except Exception:
        fingers['thumb'] = 0
    for tip in [8, 12, 16, 20]:
        name = {8: 'index', 12: 'middle', 16: 'ring', 20: 'pinky'}[tip]
        try:
            fingers[name] = 1 if lm[tip].y < lm[pip_ids[tip]].y else 0
        except Exception:
            fingers[name] = 0
    total = sum(fingers.values())
    return total, fingers

def landmark_to_pixel(landmark, w, h):
    return int(landmark.x * w), int(landmark.y * h)

# ------------------ Simple minijuego "Catch" ------------------

class SimpleCatchGame:
    def __init__(self, w, h):
        self.w = w
        self.h = h
        self.reset()

    def reset(self):
        self.target_radius = 30
        self.target_pos = (np.random.randint(50, self.w - 50), np.random.randint(50, self.h - 50))
        self.score = 0
        self.last_catch = time.time()

    def update_and_check(self, finger_pos):
        if finger_pos is None:
            return False
        d = np.linalg.norm(np.array(finger_pos) - np.array(self.target_pos))
        caught = d < (self.target_radius + 24)
        if caught:
            self.score += 1
            self.target_pos = (np.random.randint(50, self.w - 50), np.random.randint(50, self.h - 50))
            self.last_catch = time.time()
        # movimiento suave
        if time.time() - self.last_catch > 0.5:
            dx = np.random.randint(-4, 5)
            dy = np.random.randint(-4, 5)
            x = np.clip(self.target_pos[0] + dx, 50, self.w - 50)
            y = np.clip(self.target_pos[1] + dy, 50, self.h - 50)
            self.target_pos = (int(x), int(y))
        return caught

# ------------------ Main loop ------------------

def process_and_annotate(img_bgr, hands, game=None):
    annotated = img_bgr.copy()
    h, w = annotated.shape[:2]
    img_rgb = cv2.cvtColor(annotated, cv2.COLOR_BGR2RGB)
    results = hands.process(img_rgb)
    finger_index_pos = None
    if results.multi_hand_landmarks:
        for hand_landmarks, handedness in zip(results.multi_hand_landmarks, results.multi_handedness):
            label = handedness.classification[0].label  # 'Left' or 'Right' as detected (after mirror if used)
            mp_drawing.draw_landmarks(annotated, hand_landmarks, mp_hands.HAND_CONNECTIONS)
            total, fingers = count_fingers(hand_landmarks, label)
            lm = hand_landmarks.landmark
            thumb_px = landmark_to_pixel(lm[4], w, h)
            index_px = landmark_to_pixel(lm[8], w, h)
            finger_index_pos = index_px
            pinch_d = int(np.linalg.norm(np.array(thumb_px) - np.array(index_px)))
            # gesture mapping
            if total == 0:
                gesture = "Puño"
            elif total == 5:
                gesture = "Mano abierta"
            elif fingers.get('index', 0) == 1 and fingers.get('middle', 0) == 1 and fingers.get('ring', 0) == 0:
                gesture = "Peace"
            elif pinch_d < 40:
                gesture = "Pinch"
            else:
                gesture = f"{total} dedos"
            cv2.putText(annotated, f"{label} {gesture}", (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 1.0, (255,255,255), 2)
            cv2.circle(annotated, thumb_px, 6, (0,255,0), -1)
            cv2.circle(annotated, index_px, 6, (0,0,255), -1)
            cv2.line(annotated, thumb_px, index_px, (255, 0, 0), 2)
            cv2.putText(annotated, f"d={pinch_d}", (index_px[0]+10, index_px[1]+10), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (200,200,0), 2)
            # show finger states
            y0 = 60
            for i,(k,v) in enumerate(fingers.items()):
                cv2.putText(annotated, f"{k}:{v}", (10, y0 + i*20), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (180,180,180), 1)
    else:
        cv2.putText(annotated, "No hands", (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 1.0, (150,150,150), 2)

    # game drawing (single-target uses index finger)
    if game is not None:
        if 'finger_index_pos' in locals() and finger_index_pos is not None:
            _ = game.update_and_check(finger_index_pos)
        # draw target and score
        cv2.circle(annotated, game.target_pos, game.target_radius, (0,165,255), -1)
        cv2.putText(annotated, f"Score: {game.score}", (w - 170, 30), cv2.FONT_HERSHEY_SIMPLEX, 1.0, (0,255,0), 2)

    return annotated

def run_colab(max_seconds=None, target_w=640, target_h=480, fps=8, show_game=True, mirror=True):
    """
    Ejecuta la demo en Colab hasta que:
      - max_seconds transcurran (si no es None), o
      - el usuario pulse el botón 'Stop Stream' creado en la página, o
      - interrumpa la celda (KeyboardInterrupt).
    Parámetros:
      mirror: si True (por defecto), voltea horizontalmente el frame ANTES de pasarlo a MediaPipe
              — así la vista es espejo y las etiquetas coinciden con la percepción del usuario.
    """
    print("Inicializando cámara en la página (permite permisos si el navegador lo solicita)...")
    res = init_camera_page()
    if not res or 'error' in str(res):
        raise RuntimeError(f"No se pudo inicializar la cámara: {res}")
    make_stop_button()

    hands = mp_hands.Hands(static_image_mode=False, max_num_hands=2,
                           min_detection_confidence=0.6, min_tracking_confidence=0.6)
    game = SimpleCatchGame(target_w, target_h) if show_game else None

    display_handle = display(IPyImage(b''), display_id=True)

    start = time.time()
    frame_count = 0
    try:
        while True:
            # Condiciones de salida
            if max_seconds is not None and (time.time() - start) > max_seconds:
                print("Tiempo máximo alcanzado, saliendo...")
                break
            if check_stop_requested():
                print("Stop solicitado desde la página.")
                break

            dataurl = capture_frame_dataurl()
            if not dataurl:
                time.sleep(0.15)
                continue
            if isinstance(dataurl, str) and dataurl.startswith('error:'):
                print("JS capture error:", dataurl)
                time.sleep(0.5)
                continue

            img = dataurl_to_cv2_img(dataurl)
            if img is None:
                time.sleep(0.15)
                continue

            # Aplicar espejo antes de procesar si mirror=True
            if mirror:
                img = cv2.flip(img, 1)

            img = cv2.resize(img, (target_w, target_h))
            annotated = process_and_annotate(img, hands, game=game)

            # encode to jpeg bytes y actualizar display
            _, jpg = cv2.imencode('.jpg', annotated, [int(cv2.IMWRITE_JPEG_QUALITY), 85])
            display_handle.update(IPyImage(data=jpg.tobytes()))
            frame_count += 1
            time.sleep(1.0 / max(1, fps))
    except KeyboardInterrupt:
        print("Interrumpido por usuario.")
    finally:
        print("Cerrando cámara y limpiando...")
        stop_camera_page()
        try:
            hands.close()
        except Exception:
            pass
        print(f"Frames procesados: {frame_count}")
        return frame_count

# Expose convenience names
__all__ = ["run_colab", "init_camera_page", "stop_camera_page", "make_stop_button"]

run_colab(max_seconds=None, fps=60)